name: Deploy to ssh server
on: 
  push:
    branches:
      - main
      
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        user: ${{ secrets.USERNAME }}
        pass: ${{ secrets.PASSWORD }}
        first_ssh: 
          whoami
          whoami
